####
#### StayInTarkov Build Workflow
####  

name: SIT Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["*"]
    types: ["opened", "edited"]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to

    env:
      SolutionName: SIT-Launcher                              
      CSProj: SIT.Launcher/SIT.Launcher.csproj                 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore all projects
    - name: dotnet Restore
      run: dotnet restore

    # Publish the Launcher as Self-Contained Single-File
    - name: dotnet Publish
      run: |
        mkdir ${{ env.SolutionName }}
        dotnet publish ${{ env.CSProj }} --self-contained true -r win-x64 /p:PublishSingleFile=true -c Release -o ${{ env.SolutionName }}
        tar -cf ${{ env.SolutionName }}.zip ${{ env.SolutionName }}
    
    # Upload artifact unless its merge to master
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.SolutionName }}
        path: ${{ env.SolutionName }}.zip
    
    # Create release from the compressed file
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.action == 'merge'
      with:
        draft: false
        generate_release_notes: true
        files: ${{ env.SolutionName }}.zip
        tag_name: release
